#!/bin/bash

# Wait for vncserver to start
pids=0
while [ $pids -ne 4 ]
do
    pids=`ps -ef | grep vncserver | grep -v 'grep' | wc -l`
    if [ $pids -ne 4 ]
    then
        echo "Waiting for vncserver to start, will check again after 2mins"  
        sleep 1
    fi
done

python send_email.py
echo "vncserver started"
